/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/cases": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Cases */
        get: operations["list_cases_api_cases_get"];
        put?: never;
        /** Create Case */
        post: operations["create_case_api_cases_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cases/{case_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Case */
        get: operations["get_case_api_cases__case_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cases/{case_id}/images": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload Image */
        post: operations["upload_image_api_cases__case_id__images_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cases/{case_id}/images/{image_id}/signed-url": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Image Signed Url
         * @description A 5-minute link to one private photo. Allowed for the case owner and for experts on escalated cases.
         *     Anyone else gets 404, the same as for an image that does not exist.
         */
        get: operations["image_signed_url_api_cases__case_id__images__image_id__signed_url_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cases/{case_id}/analyze": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Analyze Case */
        post: operations["analyze_case_api_cases__case_id__analyze_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cases/{case_id}/follow-up": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Follow Up
         * @description Farmer answers a question and/or adds a photo; the orchestrator re-runs on the updated case.
         *
         *     To answer a structured question from `follow_up_options`, send its `question_id` and, for choice
         *     questions, the chosen `option` code.
         */
        post: operations["follow_up_api_cases__case_id__follow_up_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cases/{case_id}/analysis": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Latest Analysis */
        get: operations["latest_analysis_api_cases__case_id__analysis_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/questions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Ask Question
         * @description Ask a text question with no photo. Creates a case (entry_point "question") and analyses it in one call.
         *
         *     The intent router decides what happens: weather, advisory, treatment-safety, expert and general questions
         *     are answered without a photo. A crop-health question needs a photo, so it returns NEEDS_BETTER_IMAGE with
         *     missing_information ["close_up_photo"]; upload a photo to the returned case_id and analyse again.
         */
        post: operations["ask_question_api_questions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/files/{token}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Serve Signed File */
        get: operations["serve_signed_file_api_files__token__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{routing_run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Run */
        get: operations["get_run_api_runs__routing_run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/weather": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Weather */
        get: operations["get_weather_api_weather_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/expert/cases": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Expert Cases */
        get: operations["list_expert_cases_api_expert_cases_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/expert/cases/{case_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Expert Case */
        get: operations["get_expert_case_api_expert_cases__case_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/expert/cases/{case_id}/review": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Review Case */
        post: operations["review_case_api_expert_cases__case_id__review_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/metrics/overview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Metrics Overview */
        get: operations["metrics_overview_api_metrics_overview_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/metrics/routes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Metrics Routes */
        get: operations["metrics_routes_api_metrics_routes_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/metrics/cost-latency": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Metrics Cost Latency */
        get: operations["metrics_cost_latency_api_metrics_cost_latency_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AdvisorySource */
        AdvisorySource: {
            /** Title */
            title: string;
            /** Publisher */
            publisher: string;
            /** Verified */
            verified: boolean;
            /**
             * Stale
             * @default false
             */
            stale: boolean;
            /**
             * Structured
             * @default false
             */
            structured: boolean;
            /**
             * Source Type
             * @default demo
             * @enum {string}
             */
            source_type: "demo" | "ingested";
            /** Published At */
            published_at?: string | null;
            /** Source Url */
            source_url?: string | null;
            /** Excerpt */
            excerpt?: string | null;
            /** Page */
            page?: number | null;
            /**
             * Retrieved At
             * Format: date-time
             */
            retrieved_at?: string;
        };
        /** Body_follow_up_api_cases__case_id__follow_up_post */
        Body_follow_up_api_cases__case_id__follow_up_post: {
            /** Answer */
            answer?: string | null;
            /** Question Id */
            question_id?: string | null;
            /** Option */
            option?: string | null;
            /** @default leaf_closeup */
            kind: components["schemas"]["ImageKind"];
            /** File */
            file?: string | null;
        };
        /** Body_upload_image_api_cases__case_id__images_post */
        Body_upload_image_api_cases__case_id__images_post: {
            kind: components["schemas"]["ImageKind"];
            /** File */
            file: string;
        };
        /**
         * CallLog
         * @description One model/tool call. Mirrors routing_runs / model_runs columns.
         */
        CallLog: {
            /** Route */
            route: string;
            /** Model */
            model: string;
            /** Latency Ms */
            latency_ms: number;
            /** Started At Ms */
            started_at_ms?: number | null;
            /**
             * Cost Usd
             * @default 0
             */
            cost_usd: number;
            /** Confidence */
            confidence?: number | null;
            /**
             * Outcome
             * @default ok
             */
            outcome: string;
            /** Error */
            error?: string | null;
            /** Output */
            output?: {
                [key: string]: unknown;
            } | unknown[] | null;
        };
        /**
         * CaseAnalysisOut
         * @description POST /analyze, POST /follow-up, POST /api/questions and GET /analysis.
         *
         *     The structured fields below mirror `result.*` so a client can read them at the top level.
         */
        CaseAnalysisOut: {
            /**
             * Routing Run Id
             * Format: uuid
             */
            routing_run_id: string;
            /**
             * Case Id
             * Format: uuid
             */
            case_id: string;
            state: components["schemas"]["DecisionState"];
            result: components["schemas"]["OrchestratorResult"];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            expert?: components["schemas"]["ExpertFeedback"] | null;
            reason_code?: components["schemas"]["ReasonCode"] | null;
            /** Reason Detail */
            reason_detail?: string | null;
            /** Confidence Band */
            confidence_band?: ("low" | "medium" | "high") | null;
            /**
             * Missing Information
             * @default []
             */
            missing_information: string[];
            follow_up_options?: components["schemas"]["FollowUpOptions"] | null;
            /**
             * Trace
             * @default []
             */
            trace: components["schemas"]["TraceStep"][];
        };
        /** CaseCreate */
        CaseCreate: {
            /** Crop */
            crop: string;
            /**
             * District
             * @default Pune
             */
            district: string;
            /** Symptom Context */
            symptom_context: string;
            /**
             * Language
             * @default en
             * @enum {string}
             */
            language: "en" | "mr";
            /** Growth Stage */
            growth_stage?: string | null;
            /** Symptom Started At */
            symptom_started_at?: string | null;
            /** Recent Rainfall */
            recent_rainfall?: string | null;
            /** Description */
            description?: string | null;
        };
        /** CaseOut */
        CaseOut: {
            /** Crop */
            crop: string;
            /**
             * District
             * @default Pune
             */
            district: string;
            /** Symptom Context */
            symptom_context: string;
            /**
             * Language
             * @default en
             * @enum {string}
             */
            language: "en" | "mr";
            /** Growth Stage */
            growth_stage?: string | null;
            /** Symptom Started At */
            symptom_started_at?: string | null;
            /** Recent Rainfall */
            recent_rainfall?: string | null;
            /** Description */
            description?: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * User Id
             * Format: uuid
             */
            user_id: string;
            /**
             * Entry Point
             * @default crop_check
             * @enum {string}
             */
            entry_point: "crop_check" | "question";
            decision_state?: components["schemas"]["DecisionState"] | null;
            /** Images */
            images?: components["schemas"]["ImageOut"][];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * Category
         * @enum {string}
         */
        Category: "healthy" | "rust_like" | "leaf_spot_like" | "insect_damage" | "unknown";
        /** CostLatencyOut */
        CostLatencyOut: {
            window: components["schemas"]["MetricsWindow"];
            /** Total Analyses */
            total_analyses: number;
            latency_per_analysis: components["schemas"]["LatencyStats"];
            /** Cost Total Usd */
            cost_total_usd: number;
            /** Cost Per Analysis Usd */
            cost_per_analysis_usd: number | null;
            /** Cost Per Case Usd */
            cost_per_case_usd: number | null;
            /** By Step */
            by_step: components["schemas"]["StepStats"][];
            /** By Tier */
            by_tier: components["schemas"]["TierStats"][];
            /** Estimated Cost Saved Usd */
            estimated_cost_saved_usd: number;
            /** Cost If Vision Always Ran Usd */
            cost_if_vision_always_ran_usd: number | null;
            /** Notes */
            notes?: string[];
        };
        /**
         * DecisionState
         * @enum {string}
         */
        DecisionState: "NEEDS_BETTER_IMAGE" | "NEEDS_MORE_CONTEXT" | "PRELIMINARY_GUIDANCE" | "EXPERT_REVIEW" | "UNSUPPORTED";
        /**
         * EscalationSnapshot
         * @description Everything the expert needs, frozen at escalation time.
         */
        EscalationSnapshot: {
            /** Question */
            question: string;
            /** Description */
            description?: string | null;
            /** District */
            district: string;
            /** Growth Stage */
            growth_stage?: string | null;
            /** Symptom Started At */
            symptom_started_at?: string | null;
            /** Recent Rainfall */
            recent_rainfall?: string | null;
            /** Intent */
            intent?: string | null;
            /** Path */
            path?: string | null;
            /** Images */
            images?: components["schemas"]["ImageOut"][];
            /** Predictions */
            predictions?: components["schemas"]["Prediction"][];
            /** Missing Information */
            missing_information?: string[];
            /** Sources */
            sources?: components["schemas"]["AdvisorySource"][];
            /** Follow Ups */
            follow_ups?: string[];
        };
        /** ExpertCaseDetail */
        ExpertCaseDetail: {
            /**
             * Case Id
             * Format: uuid
             */
            case_id: string;
            escalation_reason_code?: components["schemas"]["ReasonCode"] | null;
            /** Escalation Reason Detail */
            escalation_reason_detail?: string | null;
            current: components["schemas"]["ExpertReviewRecord"];
            /** History */
            history: components["schemas"]["ExpertReviewRecord"][];
        };
        /** ExpertCaseSummary */
        ExpertCaseSummary: {
            /**
             * Case Id
             * Format: uuid
             */
            case_id: string;
            /**
             * Expert Review Id
             * Format: uuid
             */
            expert_review_id: string;
            status: components["schemas"]["ExpertStatus"];
            /** Escalation Reason */
            escalation_reason: string;
            escalation_reason_code?: components["schemas"]["ReasonCode"] | null;
            /** Escalation Reason Detail */
            escalation_reason_detail?: string | null;
            /** District */
            district: string;
            /** Question */
            question: string;
            decision_state?: components["schemas"]["DecisionState"] | null;
            /** Image Ids */
            image_ids?: string[];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * ExpertFeedback
         * @description What the farmer sees about the expert side of their case.
         */
        ExpertFeedback: {
            status: components["schemas"]["ExpertStatus"];
            decision?: components["schemas"]["ReviewDecision"] | null;
            label?: components["schemas"]["Category"] | null;
            /** Notes */
            notes?: string | null;
            recommended_advisory?: components["schemas"]["RecommendedAdvisory"] | null;
            /** Reviewed At */
            reviewed_at?: string | null;
        };
        /** ExpertReviewRecord */
        ExpertReviewRecord: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Case Id
             * Format: uuid
             */
            case_id: string;
            /**
             * Routing Run Id
             * Format: uuid
             */
            routing_run_id: string;
            status: components["schemas"]["ExpertStatus"];
            /** Escalation Reason */
            escalation_reason: string;
            snapshot: components["schemas"]["EscalationSnapshot"];
            decision?: components["schemas"]["ReviewDecision"] | null;
            label?: components["schemas"]["Category"] | null;
            /** Notes */
            notes?: string | null;
            recommended_advisory?: components["schemas"]["RecommendedAdvisory"] | null;
            /** Reviewer Id */
            reviewer_id?: string | null;
            /** Reviewed At */
            reviewed_at?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * ExpertStatus
         * @enum {string}
         */
        ExpertStatus: "pending_review" | "awaiting_farmer" | "reviewed" | "follow_up_received";
        /**
         * FollowUpOptions
         * @description A structured follow-up question. The client renders its own wording per question_id and option code.
         */
        FollowUpOptions: {
            /** Question Id */
            question_id: string;
            /**
             * Answer Type
             * @enum {string}
             */
            answer_type: "choice" | "photo" | "text";
            /** Options */
            options?: string[];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * ImageKind
         * @enum {string}
         */
        ImageKind: "leaf_closeup" | "field_overview";
        /** ImageOut */
        ImageOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Case Id
             * Format: uuid
             */
            case_id: string;
            kind: components["schemas"]["ImageKind"];
            /** Storage Path */
            storage_path: string;
            /** Content Type */
            content_type: string;
            /** Size Bytes */
            size_bytes: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * Intent
         * @enum {string}
         */
        Intent: "crop_health_image" | "general_crop_question" | "weather_context" | "advisory_lookup" | "treatment_safety" | "expert_escalation" | "unsupported_request";
        /** LatencyStats */
        LatencyStats: {
            /** N */
            n: number;
            /** Avg Ms */
            avg_ms?: number | null;
            /** P50 Ms */
            p50_ms?: number | null;
            /** P95 Ms */
            p95_ms?: number | null;
            /** Max Ms */
            max_ms?: number | null;
        };
        /** MetricsWindow */
        MetricsWindow: {
            /** Days */
            days: number | null;
            /** Since */
            since: string | null;
            /**
             * Generated At
             * Format: date-time
             */
            generated_at: string;
        };
        /** OrchestratorResult */
        OrchestratorResult: {
            state: components["schemas"]["DecisionState"];
            /** Reason */
            reason: string;
            reason_code?: components["schemas"]["ReasonCode"] | null;
            /** Reason Detail */
            reason_detail?: string | null;
            /** Message */
            message: string;
            /** Follow Up Question */
            follow_up_question?: string | null;
            follow_up_options?: components["schemas"]["FollowUpOptions"] | null;
            preliminary_label?: components["schemas"]["Category"] | null;
            /** Confidence */
            confidence?: number | null;
            /** Confidence Band */
            confidence_band?: ("low" | "medium" | "high") | null;
            /** Missing Information */
            missing_information?: string[];
            /** Sources */
            sources?: components["schemas"]["AdvisorySource"][];
            /** Route Trace */
            route_trace?: string[];
            /** Trace */
            trace?: components["schemas"]["TraceStep"][];
            /** Calls */
            calls?: components["schemas"]["CallLog"][];
            /**
             * Total Latency Ms
             * @default 0
             */
            total_latency_ms: number;
            /**
             * Total Cost Usd
             * @default 0
             */
            total_cost_usd: number;
            intent?: components["schemas"]["Intent"] | null;
            /** Intent Confidence */
            intent_confidence?: number | null;
            /** Intent Rule */
            intent_rule?: string | null;
            /** Path */
            path?: string | null;
            /** Skipped Steps */
            skipped_steps?: string[];
            /**
             * Estimated Cost Saved Usd
             * @default 0
             */
            estimated_cost_saved_usd: number;
        };
        /** Overview */
        Overview: {
            window: components["schemas"]["MetricsWindow"];
            /** Total Cases */
            total_cases: number;
            /** Total Analyses */
            total_analyses: number;
            latency_per_analysis: components["schemas"]["LatencyStats"];
            /** Cost Total Usd */
            cost_total_usd: number;
            /** Cost Per Case Usd */
            cost_per_case_usd: number | null;
            /** Cost Per Analysis Usd */
            cost_per_analysis_usd: number | null;
            escalation_rate: components["schemas"]["Rate"];
            abstention_rate: components["schemas"]["Rate"];
            vision_abstention_rate: components["schemas"]["Rate"];
            retrieval_success_rate: components["schemas"]["Rate"];
            cache_hit_rate: components["schemas"]["Rate"];
            /** Weather Sources */
            weather_sources: {
                [key: string]: number;
            };
            /** Model Disagreement Count */
            model_disagreement_count: number;
            /** Decision States */
            decision_states: {
                [key: string]: number;
            };
            /** Notes */
            notes?: string[];
        };
        /** PathStats */
        PathStats: {
            /** Path */
            path: string;
            /** Count */
            count: number;
            /** Share */
            share: number;
            /** Avg Latency Ms */
            avg_latency_ms: number | null;
            /** Avg Cost Usd */
            avg_cost_usd: number | null;
            /** Decision States */
            decision_states: {
                [key: string]: number;
            };
        };
        /** Prediction */
        Prediction: {
            /** Step */
            step: string;
            /** Model Name */
            model_name: string;
            /** Label */
            label?: string | null;
            /** Confidence */
            confidence?: number | null;
            /** Confidence Band */
            confidence_band?: ("low" | "medium" | "high") | null;
            /** Output */
            output?: {
                [key: string]: unknown;
            } | unknown[] | null;
        };
        /**
         * QuestionCreate
         * @description POST /api/questions: ask a text question with no photo. The intent router decides what happens.
         */
        QuestionCreate: {
            /** Question */
            question: string;
            /**
             * District
             * @default Pune
             */
            district: string;
            /**
             * Language
             * @default en
             * @enum {string}
             */
            language: "en" | "mr";
        };
        /**
         * Rate
         * @description numerator / denominator, with the counts shown. rate is None when there is nothing to divide by.
         */
        Rate: {
            /** Numerator */
            numerator: number;
            /** Denominator */
            denominator: number;
            /** Rate */
            rate: number | null;
        };
        /**
         * ReasonCode
         * @description Stable machine codes for why a decision was made. Clients build their own (English / Marathi) text from
         *     these. `reason` in responses is `<code>` or `<code>:<detail>`; reason_code and reason_detail split it.
         * @enum {string}
         */
        ReasonCode: "quality_failed" | "crop_not_soybean" | "farmer_requested_expert" | "unsupported_request" | "intent_unclear" | "treatment_needs_expert" | "treatment_verified_source" | "weather_context" | "advisory_lookup" | "general_crop_question" | "low_confidence_request_evidence" | "low_confidence_escalate" | "models_conflict" | "label_unknown" | "mid_confidence" | "high_confidence" | "sources_unavailable";
        /** RecommendedAdvisory */
        RecommendedAdvisory: {
            /** Title */
            title: string;
            /** Publisher */
            publisher: string;
            /** Url */
            url?: string | null;
        };
        /**
         * ReviewDecision
         * @enum {string}
         */
        ReviewDecision: "likely" | "insufficient" | "request_more" | "unknown";
        /** ReviewIn */
        ReviewIn: {
            decision: components["schemas"]["ReviewDecision"];
            /**
             * Notes
             * @default
             */
            notes: string;
            label?: components["schemas"]["Category"] | null;
            recommended_advisory?: components["schemas"]["RecommendedAdvisory"] | null;
        };
        /** RoutesOut */
        RoutesOut: {
            window: components["schemas"]["MetricsWindow"];
            /** Total Analyses */
            total_analyses: number;
            /** By Path */
            by_path: components["schemas"]["PathStats"][];
            /** By Intent */
            by_intent: {
                [key: string]: number;
            };
            /** By Decision State */
            by_decision_state: {
                [key: string]: number;
            };
            vision_call_rate: components["schemas"]["Rate"];
            /** Skipped Steps */
            skipped_steps: {
                [key: string]: number;
            };
            /** Estimated Cost Saved Usd */
            estimated_cost_saved_usd: number;
        };
        /** RunStep */
        RunStep: {
            /** Step */
            step: string;
            /** Model Name */
            model_name: string;
            /** Latency Ms */
            latency_ms: number;
            /** Cost Usd */
            cost_usd: number;
            /** Confidence */
            confidence?: number | null;
            /** Predicted Label */
            predicted_label?: string | null;
            /** Outcome */
            outcome: string;
            /** Error */
            error?: string | null;
        };
        /**
         * RunTrace
         * @description GET /api/runs/{routing_run_id}: the full route trace of one analysis.
         */
        RunTrace: {
            /**
             * Routing Run Id
             * Format: uuid
             */
            routing_run_id: string;
            /**
             * Case Id
             * Format: uuid
             */
            case_id: string;
            decision_state: components["schemas"]["DecisionState"] | null;
            /** Reason */
            reason: string | null;
            reason_code: components["schemas"]["ReasonCode"] | null;
            /** Reason Detail */
            reason_detail: string | null;
            /** Confidence Band */
            confidence_band: ("low" | "medium" | "high") | null;
            /** Intent */
            intent: string | null;
            /** Intent Confidence */
            intent_confidence: number | null;
            /** Intent Rule */
            intent_rule: string | null;
            /** Path */
            path: string;
            /** Route Trace */
            route_trace: string[];
            /** Trace */
            trace: components["schemas"]["TraceStep"][];
            /** Steps */
            steps: components["schemas"]["RunStep"][];
            /** Skipped Steps */
            skipped_steps: string[];
            /** Estimated Cost Saved Usd */
            estimated_cost_saved_usd: number;
            /** Total Latency Ms */
            total_latency_ms: number;
            /** Total Cost Usd */
            total_cost_usd: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** SignedUrlOut */
        SignedUrlOut: {
            /**
             * Image Id
             * Format: uuid
             */
            image_id: string;
            /**
             * Case Id
             * Format: uuid
             */
            case_id: string;
            kind: components["schemas"]["ImageKind"];
            /** Content Type */
            content_type: string;
            /** Url */
            url: string;
            /** Expires In */
            expires_in: number;
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
        };
        /** StepStats */
        StepStats: {
            /** Step */
            step: string;
            /** Tier */
            tier: string;
            /** Calls */
            calls: number;
            /** Errors */
            errors: number;
            latency: components["schemas"]["LatencyStats"];
            /** Total Cost Usd */
            total_cost_usd: number;
            /** Avg Cost Usd */
            avg_cost_usd: number | null;
        };
        /** TierStats */
        TierStats: {
            /** Tier */
            tier: string;
            /** Description */
            description: string;
            /** Calls */
            calls: number;
            /** Share Of Calls */
            share_of_calls: number | null;
            /** Total Cost Usd */
            total_cost_usd: number;
            /** Share Of Cost */
            share_of_cost: number | null;
        };
        /**
         * TraceStep
         * @description One step of the recorded run, in canonical order, ready for a client to replay.
         */
        TraceStep: {
            /** Step */
            step: string;
            /** Position */
            position: number;
            /**
             * Status
             * @enum {string}
             */
            status: "completed" | "failed" | "skipped";
            /** Model Name */
            model_name?: string | null;
            /** Started At Ms */
            started_at_ms?: number | null;
            /** Latency Ms */
            latency_ms?: number | null;
            /**
             * Cost Usd
             * @default 0
             */
            cost_usd: number;
            /** Confidence */
            confidence?: number | null;
            /** Confidence Band */
            confidence_band?: ("low" | "medium" | "high") | null;
            /** Outcome */
            outcome?: string | null;
            /** Error */
            error?: string | null;
            /** Skipped Reason */
            skipped_reason?: string | null;
            /** Detail */
            detail?: {
                [key: string]: unknown;
            };
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** WeatherResult */
        WeatherResult: {
            /** Available */
            available: boolean;
            /**
             * Source
             * @default unavailable
             * @enum {string}
             */
            source: "live" | "cached" | "demo" | "unavailable";
            /** Provider */
            provider?: string | null;
            /** District */
            district?: string | null;
            /** Observed At */
            observed_at?: string | null;
            /** Fetched At */
            fetched_at?: string | null;
            /**
             * Stale
             * @default false
             */
            stale: boolean;
            /** Temperature C */
            temperature_c?: number | null;
            /** Humidity Pct */
            humidity_pct?: number | null;
            /** Precipitation Mm */
            precipitation_mm?: number | null;
            /** Rain Next 24H Mm */
            rain_next_24h_mm?: number | null;
            /** Rain Probability Max Pct */
            rain_probability_max_pct?: number | null;
            /** Wind Speed Kmh */
            wind_speed_kmh?: number | null;
            /** Error */
            error?: string | null;
            /**
             * Summary
             * @default
             */
            summary: string;
            /**
             * Source Label
             * @description Human-readable provenance, shown to farmers and returned by the API.
             */
            readonly source_label: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_cases_api_cases_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CaseOut"][];
                };
            };
        };
    };
    create_case_api_cases_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CaseCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CaseOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_case_api_cases__case_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                case_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CaseOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_image_api_cases__case_id__images_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                case_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_image_api_cases__case_id__images_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImageOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    image_signed_url_api_cases__case_id__images__image_id__signed_url_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                case_id: string;
                image_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SignedUrlOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    analyze_case_api_cases__case_id__analyze_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                case_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CaseAnalysisOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    follow_up_api_cases__case_id__follow_up_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                case_id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "multipart/form-data": components["schemas"]["Body_follow_up_api_cases__case_id__follow_up_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CaseAnalysisOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    latest_analysis_api_cases__case_id__analysis_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                case_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CaseAnalysisOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ask_question_api_questions_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["QuestionCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CaseAnalysisOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    serve_signed_file_api_files__token__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                token: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_run_api_runs__routing_run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                routing_run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunTrace"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_weather_api_weather_get: {
        parameters: {
            query?: {
                district?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WeatherResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_expert_cases_api_expert_cases_get: {
        parameters: {
            query?: {
                status?: "pending_review" | "awaiting_farmer" | "reviewed" | "follow_up_received" | "all";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExpertCaseSummary"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_expert_case_api_expert_cases__case_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                case_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExpertCaseDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    review_case_api_expert_cases__case_id__review_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                case_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReviewIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExpertReviewRecord"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    metrics_overview_api_metrics_overview_get: {
        parameters: {
            query?: {
                /** @description Only include analyses from the last N days (default: all time) */
                days?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Overview"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    metrics_routes_api_metrics_routes_get: {
        parameters: {
            query?: {
                /** @description Only include analyses from the last N days (default: all time) */
                days?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoutesOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    metrics_cost_latency_api_metrics_cost_latency_get: {
        parameters: {
            query?: {
                /** @description Only include analyses from the last N days (default: all time) */
                days?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CostLatencyOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
}
