/**
 * Marathi translations of the advisory source passages (data/advisories/excerpts.json), keyed by the exact English
 * passage. Generated; a test checks that every passage has one. These are DRAFT translations for a native speaker to
 * review: the result page labels them as a translation and keeps the English original one click away.
 */
export const EXCERPTS_MR: Readonly<Record<string, string>> = {
  "This is a disease of fungal origin caused by Phakopsora pachyrhizi. Very often, it is observed during the flowering stage. Rains during these period (July- September) result in low temperature (22-27 degree celcius) and high humidity (80-90%) keeps the leaf surface moist/wet for 3-4 hours continuously which further increases the chances of incidence of rust. Night/morning fog also increases the possibility of rust infection. Pathogen survives mainly in collateral hosts. Initially chlorotic gray brown spots appear on the leaves, abundantly on lower surface. Slowly spots increase in size to form pustules. Eventually, leaves turn brown within short time causing early defoliation and reduction in number of pods, seeds and seed weight. Presence of loose brown powder owing to rupture of pustules is a characteristic symptom.":
    "हा रोग Phakopsora pachyrhizi या बुरशीमुळे होतो. तो बहुतेक वेळा फुलोऱ्याच्या अवस्थेत दिसून येतो. या काळात (जुलै–सप्टेंबर) पडणाऱ्या पावसामुळे तापमान कमी (22-27 अंश सेल्सिअस) आणि आर्द्रता जास्त (80-90%) राहते, त्यामुळे पानांचा पृष्ठभाग सलग 3-4 तास ओलसर राहतो आणि तांबेरा येण्याची शक्यता आणखी वाढते. रात्रीचे किंवा सकाळचे धुकेही तांबेऱ्याच्या संसर्गाची शक्यता वाढवते. रोगकारक मुख्यतः इतर यजमान वनस्पतींवर टिकून राहतो. सुरुवातीला पानांवर, विशेषतः खालच्या बाजूला मोठ्या प्रमाणात, फिकट करड्या-तपकिरी रंगाचे ठिपके दिसतात. हळूहळू ठिपके मोठे होऊन त्यांचे फोड तयार होतात. शेवटी पाने थोड्याच काळात तपकिरी होतात, त्यामुळे पाने लवकर गळतात आणि शेंगा, दाण्यांची संख्या व दाण्यांचे वजन कमी होते. फोड फुटल्यामुळे दिसणारी सैल तपकिरी भुकटी हे या रोगाचे वैशिष्ट्यपूर्ण लक्षण आहे.",
  "1.Soybean cultivation during rabi and summer facilitate disease cycle of rust pathogen. To break this, soybean cultivation is recommended only during kharif season. Removal ofself grown plants of rabi season. Avoid using seed of affected area for sowing in the next season. 2.Use clean healthy and disease free seeds from authentic sources.":
    "1.रब्बी आणि उन्हाळी हंगामात सोयाबीनची लागवड केल्याने तांबेरा रोगकारकाचे रोगचक्र चालू राहते. ते तोडण्यासाठी सोयाबीनची लागवड फक्त खरीप हंगामातच करण्याची शिफारस केली जाते. रब्बी हंगामात आपोआप उगवलेली झाडे काढून टाका. बाधित भागातील बियाणे पुढील हंगामात पेरणीसाठी वापरू नका. 2.विश्वसनीय स्रोतांकडून स्वच्छ, निरोगी आणि रोगमुक्त बियाणे वापरा.",
  "Soybean is infested by a complex of semiloopers. Differing in colour, shape and size, the young larvae initially cut small holes on foliage and later on completely devour the plants. In the event of heavy incidence they also damage buds, flowers and young pods resulting in non-pod formation situation. Its infestation is found to be more in the areas with less rain coupled with high temperature and humidity and causes heavy yield losses.":
    "सोयाबीनवर उंटअळ्यांच्या (सेमीलूपर) अनेक प्रजातींचा प्रादुर्भाव होतो. रंग, आकार आणि आकारमानात वेगवेगळ्या असलेल्या लहान अळ्या सुरुवातीला पानांवर लहान छिद्रे पाडतात आणि नंतर झाडे पूर्णपणे फस्त करतात. जास्त प्रादुर्भाव झाल्यास त्या कळ्या, फुले आणि कोवळ्या शेंगांचेही नुकसान करतात, त्यामुळे शेंगा लागत नाहीत. कमी पाऊस आणि त्यासोबत जास्त तापमान व आर्द्रता असलेल्या भागांत याचा प्रादुर्भाव जास्त आढळतो आणि उत्पादनाचे मोठे नुकसान होते.",
  "1.Use recommended seed rate. Avoid higher plant population as it attracts the insect causing heavy infestation. 2.Avoid higher use of nitrogenous fertilizers as it invites more insects. 3.Use bird perches at 8-10 locations in the field facilitating birds to feed on insect larvae. 4.Regular monitoring of the field and destruction of egg mass / caterpillar in early stage.":
    "1.शिफारस केलेल्या प्रमाणातच बियाणे वापरा. झाडांची संख्या जास्त ठेवू नका, कारण त्यामुळे कीड आकर्षित होऊन मोठा प्रादुर्भाव होतो. 2.नत्रयुक्त खतांचा जास्त वापर टाळा, कारण त्यामुळे जास्त कीड येते. 3.शेतात 8-10 ठिकाणी पक्षी थांबे लावा, म्हणजे पक्षी अळ्या खाऊ शकतील. 4.शेताची नियमित पाहणी करा आणि अंड्यांचे पुंजके / अळ्या सुरुवातीच्या अवस्थेतच नष्ट करा.",
  "YMD caused by Mungbean Yellow Mosaic India Virus (MYMIV) is one of the important constraints to soybean in Central India, while Mungbean Yellow Mosaic Virus (MYMV) in South India. Initially small yellow patches or spots appear on young leaves. The next trifoliate leaves emerging from the growing apex show irregular yellow and green patches alternating with each other. The yellow discoloration slowly increases and newly formed leaves may completely turn yellow. Infected leaves also show severe mottling and crinkling of leaves. The infected plants normally mature late and bear a very few flowers and pods. The pods are small and distorted. The early infection causes death of the plant before seed set. The infection results in decrease in oil. The virus is sap transmitted and spread by white fly Bemisia tabaci in semi persistence manner. The YMV has a wide host range, which includes pulses and weeds.":
    "पिवळा मोझॅक रोग (YMD) मध्य भारतात मूग पिवळा मोझॅक इंडिया विषाणूमुळे (MYMIV), तर दक्षिण भारतात मूग पिवळा मोझॅक विषाणूमुळे (MYMV) होतो आणि तो सोयाबीनसाठी एक महत्त्वाची अडचण आहे. सुरुवातीला कोवळ्या पानांवर लहान पिवळे चट्टे किंवा ठिपके दिसतात. शेंड्यातून येणाऱ्या पुढील त्रिदली पानांवर पिवळे आणि हिरवे चट्टे आलटून पालटून अनियमितपणे दिसतात. पिवळेपणा हळूहळू वाढतो आणि नवीन पाने पूर्णपणे पिवळी होऊ शकतात. बाधित पानांवर तीव्र ठिपकेदारपणा आणि सुरकुत्याही दिसतात. बाधित झाडे सहसा उशिरा पक्व होतात आणि त्यांना फारच कमी फुले व शेंगा लागतात. शेंगा लहान आणि वेड्यावाकड्या असतात. लवकर संसर्ग झाल्यास दाणे भरण्याआधीच झाड मरते. संसर्गामुळे तेलाचे प्रमाण कमी होते. हा विषाणू रसाद्वारे पसरतो आणि पांढरी माशी (Bemisia tabaci) त्याचा प्रसार करते. YMV चे यजमान अनेक आहेत, ज्यात कडधान्ये आणि तण यांचा समावेश आहे.",
  "Observe five leaves from each plant (lower, middle and upper parts) and observe the symptoms. Count the total number of infected leaves and calculate the severity.":
    "प्रत्येक झाडाची पाच पाने (खालची, मधली आणि वरची) निवडून लक्षणे पाहा. बाधित पानांची एकूण संख्या मोजा आणि रोगाची तीव्रता काढा.",
  "Cleaning of infected stubbles followed by deep summer ploughing, optimal fertilizer application, timely sowing, proper seedbed conditions and depth of sowing, optimum seeding rate and plant population, regular scouting, rogueing and destruction of infected crop/plant parts, elimination of collateral/alternate and reservoir hosts, crop rotation and intercropping, cultivation of soybean in rainy season only and avoidance of mono varietal culture.":
    "बाधित पिकाचे अवशेष स्वच्छ करून उन्हाळ्यात खोल नांगरणी, खतांचा योग्य वापर, वेळेवर पेरणी, योग्य वाफा आणि पेरणीची योग्य खोली, योग्य बियाणे प्रमाण आणि झाडांची संख्या, नियमित पाहणी, बाधित पीक/झाडांचे भाग उपटून नष्ट करणे, पर्यायी आणि आश्रय देणाऱ्या यजमान वनस्पतींचा नाश, पीक फेरपालट आणि आंतरपीक, सोयाबीनची लागवड फक्त पावसाळी हंगामात करणे आणि एकाच वाणाची लागवड टाळणे.",
  "Surveillance on disease incidence and severity in the main field should be done along with insect-pest just after crop sowing/transplanting and at weekly intervals thereafter. In each of the field select 20 plants diagonally and observe, stem, leaves, fruits, etc. for disease symptoms & severity.":
    "मुख्य शेतात पेरणी/लागवडीनंतर लगेच आणि त्यानंतर दर आठवड्याला किडींसोबतच रोगांचा प्रादुर्भाव आणि तीव्रता यांची पाहणी करावी. प्रत्येक शेतात तिरप्या रेषेत 20 झाडे निवडून खोड, पाने, फळे इत्यादींवर रोगाची लक्षणे आणि तीव्रता तपासा.",
  "Field scouting should be undertaken by the farmers/ extension functionaries to keep a close watch on the appearance of insect pest, disease and bio-control fauna.":
    "शेतकरी/विस्तार कार्यकर्त्यांनी शेतात फिरून पाहणी करावी आणि कीड, रोग व मित्र कीटकांच्या आगमनावर बारीक लक्ष ठेवावे.",
  "Disease: Myrothecium leaf spot. Pathogen: Myrothecium roridum Tode. Scouting: Flowering to pod filling stage. States: M.P., Rajasthan, Karnataka, A.P., Maharashtra and Uttarakhand.":
    "रोग: मायरोथेसियम पानावरील ठिपके (Myrothecium leaf spot). रोगकारक: Myrothecium roridum Tode. पाहणीचा काळ: फुलोऱ्यापासून शेंगा भरण्याच्या अवस्थेपर्यंत. राज्ये: मध्य प्रदेश, राजस्थान, कर्नाटक, आंध्र प्रदेश, महाराष्ट्र आणि उत्तराखंड.",
  "Disease: Frog eye leaf spot. Pathogen: Cercospora sojina K.Hara. Scouting: Flowering to seed set.":
    "रोग: फ्रॉग आय पानावरील ठिपके (Frog eye leaf spot). रोगकारक: Cercospora sojina K.Hara. पाहणीचा काळ: फुलोऱ्यापासून दाणे भरण्यापर्यंत.",
  "Resistant/tolerant varieties for Frog eye leaf spot: Bragg, JS 80-21, KHSb 2 and VLS 21. Resistant/tolerant varieties for Myrothecium leaf spot: JS 71-05, JS 335, MACS 13, MACS 124, MAUS 47 and NRC 7.":
    "फ्रॉग आय पानावरील ठिपके रोगास प्रतिकारक/सहनशील वाण: Bragg, JS 80-21, KHSb 2 आणि VLS 21. मायरोथेसियम पानावरील ठिपके रोगास प्रतिकारक/सहनशील वाण: JS 71-05, JS 335, MACS 13, MACS 124, MAUS 47 आणि NRC 7.",
};
